services:
  - type: web
    name: health-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn health_api.wsgi:application --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: doadmin
      - key: DB_PASSWORD
        value: YOUR_DB_PASSWORD_HERE
      - key: DB_HOST
        value: db-postgresql-nyc3-88942-do-user-19716193-0.i.db.ondigitalocean.com
      - key: DB_PORT
        value: 25060
